apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gcloud-api
  links:
    - url: http://gcloud.com/v1
      title: Gcloud
      icon: dashboard
  description: API to fetch info from Google cloud
spec:
  type: openapi
  lifecycle: experimental
  owner: user:fotisolgr
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Gcloud API
      license:
        name: MIT
    servers:
      - url: http://gcloud.com/v1
      - url: http://staging.gcloud.com
    paths:
      /projects:
        get:
          summary: Returns a list of gcloud projects.
          responses:
            '200':    # status code
              description: A JSON array of gcloud projects
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string
      /user:                
        post:
          summary: Create gcloud project.
          responses:
            '201':    # status code
              description: A JSON array of gcloud projects
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string
